boook1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import myauth.urls as myauth
import mycontent.urls as mycontent
from boook1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(myauth)),
    path('mycart/', include('mycart.urls', namespace='mycart')),
    path('', include(mycontent)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycart/urls.py
from django.urls import path
from . import views

app_name = 'mycart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>', views.cart_add, name='cart_add'),
    path('remove/<int:book_id>', views.cart_remove, name='cart_remove'),

]

mycontent/urls.py
from django.urls import path

from boook1 import settings
from mycontent import views

app_name = 'mycontent'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('book/<slug:book_slug>', views.book, name='book'),
    path('create/', views.book_create, name='book_create'),
    path('search_result/', views.search_result, name='search_result'),
]

mycart/models.py
from django.db import models

# Create your models here.

mycart/forms.py
from django import forms

BOOK_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddBookForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=BOOK_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mycart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from mycontent.models import Book
from .cart import Cart
from .forms import CartAddBookForm


@require_POST
def cart_add(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    form = CartAddBookForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book=book, quantity=cd['quantity'], override_quantity=cd['override'])

    # import pdb;pdb.set_trace()
    return redirect('mycart:cart_detail')


def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)
    return redirect('mycart:cart_detail')


def cart_detail(request):
    cart = Cart(request)

    return render(request, 'mycart/detail.html', {'cart': cart})

mycart/templates/mycart/detail.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
{% block title %}Shoping Cart{% endblock %}

{% block content %}
<h1>Shoping Cart</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit Price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>

   {% for item in cart %}
    {% with book=item.book %}
    <tr>
        <td>
            <a href="{{ book.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% endif %}">
{#                         {% else %}{% static "badanmaar.png" %}{% endif %}">#}
            </a>
        </td>
    <td> {{ book.title }}</td>
    <td> {{ item.quantity }}</td>
    <td>
        <form action='{% url "mycart:cart_remove" book.id %}' method="POST">
            {% csrf_token %}
            <input type="submit" value="Remove">
        </form>

    </td>
    <td class="num">T{{ item.price }}</td>
    <td class="num">T{{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">T{{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url "mycontent:landing_page" %}" class="buttonlight">Continue Shopping</a>
    <a href="#" class="button">CheckOut</a>
</p>
{% endblock %}