boook1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import myauth.urls as myauth
import mycontent.urls as mycontent
from boook1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(myauth)),
    path('mycart/', include('mycart.urls', namespace='mycart')),
    path('', include(mycontent)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myauth/urls.py
from django.contrib.auth import views
from django.urls import path, include
from .views import sign_up
app_name = 'myauth'
urlpatterns = [
    path('', include("django.contrib.auth.urls")),
    path('sign_up/', sign_up, name='sign_up'),

]

mycontent/urls.py
from django.urls import path

from boook1 import settings
from mycontent import views

app_name = 'mycontent'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('book/<slug:book_slug>', views.book, name='book'),
    path('create/', views.book_create, name='book_create'),
    path('search_result/', views.search_result, name='search_result'),
]

mycontent/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Count
from django.urls import reverse
from django.utils.text import slugify
# from myshop.models import Price
import myauth.models


class Book(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True, unique=True)
    mytranslator = models.ManyToManyField('myauth.Translator',)
    cover = models.ImageField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    description = models.TextField()
    author = models.ManyToManyField('myauth.Author',)
    publisher = models.ForeignKey('myauth.Publisher', on_delete=models.CASCADE, null=True)
    category = models.ManyToManyField('myauth.Category',)
    active = models.BooleanField(default=True)
    file = models.FileField(upload_to='filamoon/', null=True)
    stars = models.DecimalField(max_digits=3, decimal_places=2, null=True)
    price = models.IntegerField(null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('mycontent:book',
                       args=[self.slug])

    @property
    def get_similar_books(self):
        book_tags_ids = self.category.values_list('id', flat=True)
        similar_books = Book.objects.filter(tag__in=book_tags_ids).exclude(id=self.id).distinct()
        similar_books = similar_books.annotate(same_tags=Count('tag')).order_by('-same_tags', '-created')
        return similar_books

    def __str__(self):
        return self.title

    def get_book_stars(self):
        book_votes_count = self.votemodel_set.all().count()
        # book_votes =

        return

    def get_price(self):
        return self.price

    def get_comments(self):
        return self.comment_set.all()

    def get_latest(self):
        return Book.objects.all().order_by('created')[0:5]

    def get_most_viewed(self):
        return None

    def get_most_liked(self):
        return None

    def get_most_discounted(self):
        return None


class Comment(models.Model):
    body = models.TextField()
    user = models.ForeignKey('myauth.MyUser', on_delete=models.CASCADE, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now_add=True)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)


class CustomModelManager(models.Manager):
    def create(self, *args, **kwargs):
        voter, newvote = kwargs.get('voter'), kwargs.get('vote')
        book, author = kwargs['book'], kwargs['author']
        if book:
            myvote = VoteModel.objects.filter(voter=voter, book=book)
        elif author:
            myvote = VoteModel.objects.filter(voter=voter, author=author)
        else:
            myvote = None
        if myvote.exists():
            prevvote = myvote.values_list('vote', flat=True).last()
            if prevvote == newvote:
                myvote.delete()
            elif prevvote != newvote:
                myvote.delete()
                super(CustomModelManager, self).create(*args, **kwargs)
        else:
            super(CustomModelManager, self).create(*args, **kwargs)


class VoteModel(models.Model):
    voter = models.ForeignKey('myauth.MyUser', on_delete=models.CASCADE, related_name='votes', unique=False)
    vote = models.IntegerField(validators=[MinValueValidator(0),
                                           MaxValueValidator(5)])

    book = models.ForeignKey(Book, null=True, on_delete=models.CASCADE)
    publisher = models.ForeignKey('myauth.Publisher', null=True, on_delete=models.CASCADE)
    author = models.ForeignKey('myauth.Author', null=True, on_delete=models.CASCADE)

    objects = CustomModelManager()

    def __str__(self):
        return self.voter.username

mycontent/forms.py
from django import forms
from .models import Book, Comment


class BookCreateForm(forms.ModelForm):
    cover = forms.ImageField(required=False)

    class Meta:
        model = Book
        fields = ('title', 'description', 'cover',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class SearchForm(forms.ModelForm):
    author = forms.CharField(max_length=20, required=False)
    title = forms.CharField(max_length=20, required=False)

    class Meta:
        model = Book
        fields = ('title', 'author')

mycontent/views.py
from django.shortcuts import render, get_object_or_404, redirect

from mycart.forms import CartAddBookForm
from mycontent.context_processors import search
from mycontent.forms import BookCreateForm
from mycontent.models import Book


def landing_page(request, ):
    latest_books = Book.get_latest(self=request)
    # most_viewed_books = Book.get_most_viewed()
    # most_liked_books = Book.get_most_liked()
    # most_discounted_books = Book.get_most_discounted()
    context = {
        'latest_books': latest_books,
        # 'most_viewed_books': most_viewed_books,
        # 'most_liked_books': most_liked_books,
        # 'most_discounted_books': most_discounted_books,
    }
    return render(request, 'mycontent/landing_page.html', context)


def search_result(request, ):
    import pdb;
    pdb.set_trace()

    if request.method == 'POST':
        form = search(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['title']:
                result = Book.objects.filter(title=cd['title'])
            if cd['title']:
                result = Book.objects.filter(title=cd['author'])
    else:
        result = None

    return render(request, 'mycontent/landing_page.html', {'result': result})


def book(request, book_slug):
    mybook = get_object_or_404(Book, slug=book_slug)
    comments = mybook.get_comments()
    cart_book_form = CartAddBookForm()
    context = {
        'book': mybook,
        'comments': comments,
        'cart_book_form': cart_book_form,
    }
    return render(request, 'mycontent/book.html', context)


def book_create(request):
    new_book = None
    user = request.user
    # if user is not
    if request.method == 'POST':
        form = BookCreateForm(data=request.POST)
        if form.is_valid():
            new_book = form.save(commit=False)

            new_book.user = user
            new_book.save()
        else:
            print('is not valid', form.errors)
    else:
        form = BookCreateForm(request.POST)
    return render(request, 'mycontent/book_create.html', context={'form': form,
                                                                  'newpost': new_book})

mycontent/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <title>Title</title>
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

{% block topnav %}

    <header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href={% url 'mycontent:landing_page' %} class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#contact" class="nav-link px-2 text-white">Contact Us</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">

          <div class="col col-lg-2" >
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
          </a>

          <div class="dropdown-menu">
  <form method="POST" class="px-4 py-3">
      {% csrf_token %}
    <div class="form-group">

      <label>Title</label>
        {{ search_form.title }}
    </div>
    <div class="form-group">
        {{ search_form.author }}
    </div>
{#          <button type="submit" formaction='{% url "mycontent:search_result" %}'  class="btn btn-primary" value="Search">Search</button>#}
          <input type="submit" formaction='{% url "mycontent:search_result" %}'  class="btn btn-primary" value="Search"/>
  </form>
</div>
        </div>

          {% if user.is_authenticated %}
          <div class="col col-lg-2" >
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            {% if user.profile_image %}
              <img src="{{ user.profile_image.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                {% else %}
                <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
            {% endif %}
          </a>
          <ul class="dropdown-menu text-small shadow">
              {% if user.is_staff %}
            <li><a class="dropdown-item" href="{% url "mycontent:book_create" %}">New Book</a></li>
              {% endif %}
            <li><a class="dropdown-item" href="#">SavedBooks</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href={% url 'myauth:logout' %}>Sign out</a></li>
          </ul>
        </div>
        {% else %}


        <div class="text-end">
          <a href={% url 'myauth:login' %}><button type="button" class="btn btn-outline-light me-2">Login</button></a>
          <a href={% url 'myauth:sign_up' %}><button type="button" class="btn btn-warning">Sign-up</button></a>
        </div>
        {% endif %}

      </div>

    </div>

  </header>
{% endblock %}
{% block content %}
{% endblock %}


{% block footer %}
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#"  class="nav-link px-2 text-muted" id="contact">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Company, Inc</p>
  </footer>
</div>
{% endblock %}
</body>
</html>