boook1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import myauth.urls as myauth
import mycontent.urls as mycontent
from boook1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(myauth)),
    path('mycart/', include('mycart.urls', namespace='mycart')),
    path('', include(mycontent)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycart/urls.py
from django.urls import path
from . import views

app_name = 'mycart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>', views.cart_add, name='cart_add'),
    path('remove/<int:book_id>', views.cart_remove, name='cart_remove'),

]

mycontent/urls.py
from django.urls import path

from boook1 import settings
from mycontent import views

app_name = 'mycontent'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('book/<slug:book_slug>', views.book, name='book'),
    path('create/', views.book_create, name='book_create'),
    path('search_result/', views.search_result, name='search_result'),
]

mycontent/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Count
from django.urls import reverse
from django.utils.text import slugify
# from myshop.models import Price
import myauth.models


class Book(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True, unique=True)
    mytranslator = models.ManyToManyField('myauth.Translator',)
    cover = models.ImageField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    description = models.TextField()
    author = models.ManyToManyField('myauth.Author',)
    publisher = models.ForeignKey('myauth.Publisher', on_delete=models.CASCADE, null=True)
    category = models.ManyToManyField('myauth.Category',)
    active = models.BooleanField(default=True)
    file = models.FileField(upload_to='filamoon/', null=True)
    stars = models.DecimalField(max_digits=3, decimal_places=2, null=True)
    price = models.IntegerField(null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('mycontent:book',
                       args=[self.slug])

    @property
    def get_similar_books(self):
        book_tags_ids = self.category.values_list('id', flat=True)
        similar_books = Book.objects.filter(tag__in=book_tags_ids).exclude(id=self.id).distinct()
        similar_books = similar_books.annotate(same_tags=Count('tag')).order_by('-same_tags', '-created')
        return similar_books

    def __str__(self):
        return self.title

    def get_book_stars(self):
        book_votes_count = self.votemodel_set.all().count()
        # book_votes =

        return

    def get_price(self):
        return self.price

    def get_comments(self):
        return self.comment_set.all()

    def get_latest(self):
        return Book.objects.all().order_by('created')[0:5]

    def get_most_viewed(self):
        return None

    def get_most_liked(self):
        return None

    def get_most_discounted(self):
        return None


class Comment(models.Model):
    body = models.TextField()
    user = models.ForeignKey('myauth.MyUser', on_delete=models.CASCADE, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now_add=True)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)


class CustomModelManager(models.Manager):
    def create(self, *args, **kwargs):
        voter, newvote = kwargs.get('voter'), kwargs.get('vote')
        book, author = kwargs['book'], kwargs['author']
        if book:
            myvote = VoteModel.objects.filter(voter=voter, book=book)
        elif author:
            myvote = VoteModel.objects.filter(voter=voter, author=author)
        else:
            myvote = None
        if myvote.exists():
            prevvote = myvote.values_list('vote', flat=True).last()
            if prevvote == newvote:
                myvote.delete()
            elif prevvote != newvote:
                myvote.delete()
                super(CustomModelManager, self).create(*args, **kwargs)
        else:
            super(CustomModelManager, self).create(*args, **kwargs)


class VoteModel(models.Model):
    voter = models.ForeignKey('myauth.MyUser', on_delete=models.CASCADE, related_name='votes', unique=False)
    vote = models.IntegerField(validators=[MinValueValidator(0),
                                           MaxValueValidator(5)])

    book = models.ForeignKey(Book, null=True, on_delete=models.CASCADE)
    publisher = models.ForeignKey('myauth.Publisher', null=True, on_delete=models.CASCADE)
    author = models.ForeignKey('myauth.Author', null=True, on_delete=models.CASCADE)

    objects = CustomModelManager()

    def __str__(self):
        return self.voter.username

mycontent/forms.py
from django import forms
from .models import Book, Comment


class BookCreateForm(forms.ModelForm):
    cover = forms.ImageField(required=False)

    class Meta:
        model = Book
        fields = ('title', 'description', 'cover',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class SearchForm(forms.ModelForm):
    author = forms.CharField(max_length=20, required=False)
    title = forms.CharField(max_length=20, required=False)

    class Meta:
        model = Book
        fields = ('title', 'author')

mycontent/views.py
from django.shortcuts import render, get_object_or_404, redirect

from mycart.forms import CartAddBookForm
from mycontent.context_processors import search
from mycontent.forms import BookCreateForm
from mycontent.models import Book


def landing_page(request, ):
    latest_books = Book.get_latest(self=request)
    # most_viewed_books = Book.get_most_viewed()
    # most_liked_books = Book.get_most_liked()
    # most_discounted_books = Book.get_most_discounted()
    context = {
        'latest_books': latest_books,
        # 'most_viewed_books': most_viewed_books,
        # 'most_liked_books': most_liked_books,
        # 'most_discounted_books': most_discounted_books,
    }
    return render(request, 'mycontent/landing_page.html', context)


def search_result(request, ):
    import pdb;
    pdb.set_trace()

    if request.method == 'POST':
        form = search(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['title']:
                result = Book.objects.filter(title=cd['title'])
            if cd['title']:
                result = Book.objects.filter(title=cd['author'])
    else:
        result = None

    return render(request, 'mycontent/landing_page.html', {'result': result})


def book(request, book_slug):
    mybook = get_object_or_404(Book, slug=book_slug)
    comments = mybook.get_comments()
    cart_book_form = CartAddBookForm()
    context = {
        'book': mybook,
        'comments': comments,
        'cart_book_form': cart_book_form,
    }
    return render(request, 'mycontent/book.html', context)


def book_create(request):
    new_book = None
    user = request.user
    # if user is not
    if request.method == 'POST':
        form = BookCreateForm(data=request.POST)
        if form.is_valid():
            new_book = form.save(commit=False)

            new_book.user = user
            new_book.save()
        else:
            print('is not valid', form.errors)
    else:
        form = BookCreateForm(request.POST)
    return render(request, 'mycontent/book_create.html', context={'form': form,
                                                                  'newpost': new_book})

mycontent/templates/mycontent/book.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
{% block title %}My amazing library{% endblock %}
{% block content %}
    <img src="{{ book.cover.url }}">

    <br>
    {{ book.title }}
    <br>
    {{ book.author }}
    <br>
    {% if book.get_price == None %}Nadarim{% else %}{{ book.get_price }}{% endif %}
    <br>
   
   <form action='{% url "mycart:cart_add" book.id %}' method="POST">
       {% csrf_token %}
       {{ cart_book_form }}
       <input type="submit" value="Add to cart">
   </form>

{% endblock %}

mycontent/templates/mycontent/book_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
{% block title %}My amazing library{% endblock %}
{% block content %}
    {% if newpost %}
 <h2>Your book has been added.</h2>
{% else %}
 <h2>Add a new book</h2>
 <form method="POST">
 {% csrf_token %}
     {{ form.title|as_crispy_field }}
     {{ form.description|as_crispy_field }}
     {{ form.cover|as_crispy_field }}
{#    <a href="{% url 'post' %}"></a>#}
          <br>

 <p><input type="submit" value="Add POST"></p>
 </form>
{% endif %}
{% endblock %}
</html>

mycontent/templates/mycontent/landing_page.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
{% block title %}My amazing library{% endblock %}
{% block content %}

    {% load thumbnail %}
    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" >
    <script src="{% static 'bootstrap.min.js' %}"></script>
{#    <script>alert();</script>#}

<div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
{#  <div class="carousel-inner py-4">#}
{% if search_input %}
{% for searched_book in search_input %}
    <a href="{{ searched_book.get_absolute_url }}">
      <div class="col">
        <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url({{ latest_books.3.cover.url }}),
url({% static 'css/abstract-grunge-decorative-relief-navy-blue-stucco-wall-texture-wide-angle-rough-colored-background_1258-28311.jpg' %});
 background-repeat: no-repeat; background-color: #b6d4fe; background-size: contain ;">
          <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
            <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold text-end shadow-lg bg-success bg-opacity-50 bg-body  bg-gradient bg rounded">{{ searched_book }}</h2>
            <ul class="d-flex list-unstyled mt-auto">
              <li class="me-auto">
    <img src="{{ book.cover.url }}" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
              </li>
              <li class="d-flex align-items-center me-3">
                <small>Price</small>
              </li>
              <li class="d-flex align-items-center">
                <small>{% if searched_book.get_price == None %}Nadarim{% else %}{{ searched_book.get_price }}{% endif %}</small>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </a>
{% endfor %}
  </div>
{% endif %}

{% for book in latest_books %}
    <a href="{{ book.get_absolute_url }}">
      <div class="col">
        <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url({{ latest_books.3.cover.url }}),
url({% static 'css/abstract-grunge-decorative-relief-navy-blue-stucco-wall-texture-wide-angle-rough-colored-background_1258-28311.jpg' %});
 background-repeat: no-repeat; background-color: #b6d4fe; background-size: contain ;">
          <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
            <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold text-end shadow-lg bg-success bg-opacity-50 bg-body  bg-gradient bg rounded">{{ book }}</h2>
            <ul class="d-flex list-unstyled mt-auto">
              <li class="me-auto">
    <img src="{{ book.cover.url }}" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
              </li>
              <li class="d-flex align-items-center me-3">
                <small>Price</small>
              </li>
              <li class="d-flex align-items-center">
                <small>{% if book.get_price == None %}Nadarim{% else %}{{ book.get_price }}{% endif %}</small>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </a>
{% endfor %}
  </div>


{% endblock %}
</html>